Repository Team-Panopticon/bookmark-dashboard, pull requests merged in 2022-03, with the labels that each got.

#57 Favicon 이미지 사이즈를 16x16 에서 64x64로 증가
  src/newtab/components/Favicon.vue
Labels: feature

#59 우상단 popup에 서비스명, 버전, 설명, 링크 정보 추가
  public/manifest.json
  src/popup/PopUp.vue
  src/popup/main.ts
  vue.config.js
Labels: feature

#63 파일/폴더 수정 삭제, 폴더 생성 시 refresh 추가
  src/newtab/components/Bookshelf.vue
  src/newtab/components/ContextMenu/ContextMenuContent.vue
  src/newtab/components/CreateFolderModal.vue
  src/newtab/components/UpdateModal.vue
  src/newtab/store/index.ts
  src/newtab/store/modules/updateModal.ts
Labels: feature

#69 fix: 누락된 컨텍스트 메뉴 아이템 툴팁 스타일
  src/newtab/components/ContextMenu/ContextMenuContent.vue
Labels: bug

#74 북마크 이벤트 핸들러를 이용해서 refreshTarget을 설정
  src/newtab/components/ContextMenu/ContextMenuContent.vue
  src/newtab/components/CreateFolderModal.vue
  src/newtab/pages/Desktop.vue
Labels: feature, refactor

#76 폴더 삭제 시 BookshelfModal close 기능 추가 / 변수명 리팩토링
  src/newtab/components/BookshelfModal.vue
  src/newtab/components/BookshelfModalContainer.vue
  src/newtab/components/ContextMenu/ContextMenuContent.vue
  src/newtab/store/modules/bookshelfModal.ts
Labels: feature, refactor

#75 전역 Bookmark 상태 제거
  src/newtab/components/CreateFolderModal.vue
  src/newtab/components/UpdateModal.vue
  src/newtab/pages/Desktop.vue
  src/newtab/store/index.ts
Labels: refactor

#77 Modal 스타일 통일
  package.json
  src/newtab/components/BookshelfModal.vue
  src/newtab/components/CreateFolderModal.vue
  src/newtab/components/UpdateModal.vue
  src/newtab/pages/Desktop.vue
  yarn.lock
Labels: feature, refactor

#85 bookshelf index -> id
  src/newtab/components/Bookshelf.vue
Labels: bug

#89 fix: 업데이트 모달 닫기시 상태 변하는 현상
  src/newtab/store/modules/updateModal.ts
Labels: bug

#93 fix: Tooltip이 bookshelf modal 영역을 확장시키던 문제 해결
  src/newtab/components/Bookshelf.vue
  src/newtab/components/Tooltip.vue
  src/newtab/pages/Desktop.vue
  src/newtab/store/index.ts
  src/newtab/store/modules/tooltip.ts
Labels: bug

#96 zip, publish 명령어 추가
  package.json
Labels: feature
